### ISSUE TITLE
le big todo

### ISSUE THREAD

**Issue by hemorej** [hemorej/invis#1]
## Technical
- [x] Upgrade kirby to 2.5

## Store
- [x] panel add print (qty, price, sizes)
- [x] product page, index page
- [x] payment integration
- [x] merge branch
### stripe sdk integration
- [x] panel: date, status, email, address, price.
- [x] order mark shipped: sync status to stripe
- [x] Order update inventory
- [x] Order on checkout
- [x] Cart update products template bug
### product crud to sync panel
- [x] create product update local id on success
- [x] create variant update local sku on success
- [x] email confirmation + notification
- [x] checkout fix order content
### cart
- [x] show cart
- [x] +/-/delete items callback
- [x] replace shopkit id with sku
- [x] if cart show link, style cart
- [x] stripe checkout callback (create order API and local)
- [x] Proper “insufficient stock message” cart.js
- [x] qty column for +/- action
- [x] responsive layout bug
- [x] noscript tag message, graceful deg
- [x] cached cart link bug
### orders
- [x] move overlay css to cart only
- [x] proper error handling
- [x] layout bug shop prices landscape format
- [x] Integrate monolog
- [x] send shipping notification email when order status changes
- [x] inventory update duplicate variant bug
- [x] add 0 to cart bug

## Design
- [x] laptop screen size mq picture touches left edges
- [x] typography scale
- [x] mq landscape orientation bug
- [x] Homepage image, larger, cropped, above title (upper 2/3)
- [x] blog template
- [x] Colour multiply on thumbnail hover
- [x] Redo archive page (see Spotify highlights page)
- [x] Different colour accents
- [x] Bigger thumbnails/images
- [x] Adjust menu/grid design
- [x] website title hidden in menu on mobile
- [x] product description text, variant/price display issues
- [x] display multiple [currencies](http://fixer.io/)? (in cart not product)
- [x] cache currency api results, error handling
- [x] Style email confirm ([heml](https://heml.io/docs/getting-started/guide))
- [x] Style order confirm
- [x] order confirm error section (detailed error message)
- [x] check inventory before charge
- [x] uidHandler, stamp shipping date in order on status change
- [x] display shipping before total, security notice (cc not stored, encrypted, email not shared) 
- [x] about content before links 
- [x] small description in cart for each item
- [x] rename "archive" to “all post”
- [x] "people I follow" instead of “links”
- [x] full width image first, content paragraph, multiple columns for links below 
- [x] travels, make title link, no pagination  
- [x] make cart button bigger 
- [x] checkout button on the right, “total” float right 
- [x] show empty cart on the side, browse prints link in empty cart 
- [x] Fix meta tags/twitter card
- [x] interchange first image bug

## Content
- [x] Replace journal/series images without borders
- [x] Move diptychs as series remove notes
- [x] Update portfolio series
- [x] draft floral series
- [x] more personal info before quote, camera, who am I. Darkroom photos, why am i doing this, is it a company?
- [x] finish replacing content
- [x] resize images smaller

## Last steps/going live
- [x] Footer/js/jquery situation
- [x] review css, consolidate rules
- [x] Minify css, cart.js
- [x] articles/products code review
- [x] cart/session code review
- [x] js file size

## Testing 
- [x] Stripe checklist
- [x] Responsive testing
- [x] staging setup (~~symlink~~, ~~charges~~, ~~openssl ids~~, ~~email delivery~~, ~~state and inventory updates~~, ~~session timeout~~, ~~exclude cart/order from cache~~, ~~disable cors~~, ~~https wrapper~~, ~~flush previous cache~~, ~~setup mailgun domain~~, ~~logging~~)
