### ISSUE TITLE
testing checklist

### ISSUE THREAD

**Issue by hemorej** [hemorej/invis#3]
### pages
- [x] shop: product, cart, order
- [x] articles/archive
- [x] article/blog
- [x] home page
### devices
- [x] firefox
- [x] safari
- [x] chrome/opera
- [x] iphone5: portrait/landscape
- [x] iphone8: portrait/landscape
- [x] ipad: portrait/landscape
- [x] 15"
- [x] 24"
## Security
- [x] review stripe dispute/best practices [disputes](https://stripe.com/docs/disputes/categories), [disputes 2](https://stripe.com/docs/disputes/prevention), [best practices](https://stripe.com/docs/sources/best-practices)
- [x] session cookie hijack
## Design
- [x] check case consistency
- [x] margin from menu consistency
- [x] hierarchy
- [x] cart link behaviour (.menu-large-space-top class in js)
- [x] meta tags
### regular flow
- [x] browse, purchase, view confirm, receive email, update inventory, shipping update
### negative cases
- [x] submit fake paypal order id
- [x] order without js
- [x] order with incomplete data
- [x] order with duplicate data
- [x] order with invalid data
- [x] inventory hack: submit qty > inventory
- [x] buy if out of stock
- [x] one of two variants out of stock, display message
- [x] all variants out of stock, display message
- [x] one of variants out of stock, correct variant in cart
- [x] payment hack: no charge
- [x] pay less than cart total
- [x] order corruption: move uid failed
- [x] order corruption: session id lost
- [x] order corruption: customer info lost
- [x] order corruption: cart/session persist after order
## Other
- [x] feed
