### ISSUE TITLE
Going live checklist

### ISSUE THREAD

**Issue by hemorej** [hemorej/invis#9]
- [x] migrate images to new content structure
- [x] install new k3 license
- [x] minify/cat css
-  stripe live checklist
    - [x] apple pay
    - [x] preview image works
- [x] PayPal live checklist

**Comment by hemorej** [comment]
Deployed
